import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from 'styles/Home.module.css'
import Sidebar from 'src/components/Sidebar'
import { useEffect, useState  } from 'react'
import { Flex } from '@chakra-ui/layout'
import ContactView from 'src/components/ContactView'
import { ContactUser, User } from 'src/types/user';


const Home: NextPage = () => {
  const [users, setUsers] = useState<Array<ContactUser>>([]);
  const [showForm, setShowForm] = useState<boolean>(false);
  const [currentUser, setCurrentUser] = useState<string | null>(null);
  useEffect(() => {
    const localUsers = localStorage.getItem('users');
    if (localUsers === null) {
      localStorage.setItem('users', JSON.stringify([]));
      setUsers([]);
    }
    else {
      setUsers(JSON.parse(localUsers));
    }
  },[ currentUser ])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <Flex>
            <Sidebar currentUser={currentUser} users={users} setCurrentUser={setCurrentUser}/>
            <ContactView currentUser={currentUser} setCurrentUser={setCurrentUser} setUsers={setUsers}/>
          </Flex>
      </main>
    </div>
  )
}

export default Home
